package unitystatistics

const (
	MetricStarts   AcquisitionMetric = "starts"
	MetricViews    AcquisitionMetric = "views"
	MetricClicks   AcquisitionMetric = "clicks"
	MetricInstalls AcquisitionMetric = "installs"
	MetricSpend    AcquisitionMetric = "spend"
	MetricCPI      AcquisitionMetric = "cpi"
	MetricCTR      AcquisitionMetric = "ctr"
	MetricCVR      AcquisitionMetric = "cvr"
	MetricECPM     AcquisitionMetric = "ecpm"

	MetricD0AdRevenue  AcquisitionMetric = "d0AdRevenue"
	MetricD1AdRevenue  AcquisitionMetric = "d1AdRevenue"
	MetricD3AdRevenue  AcquisitionMetric = "d3AdRevenue"
	MetricD7AdRevenue  AcquisitionMetric = "d7AdRevenue"
	MetricD14AdRevenue AcquisitionMetric = "d14AdRevenue"
	MetricD21AdRevenue AcquisitionMetric = "d21AdRevenue"
	MetricD28AdRevenue AcquisitionMetric = "d28AdRevenue"

	MetricD0AdRevenueROAS  AcquisitionMetric = "d0AdRevenueRoas"
	MetricD1AdRevenueROAS  AcquisitionMetric = "d1AdRevenueRoas"
	MetricD3AdRevenueROAS  AcquisitionMetric = "d3AdRevenueRoas"
	MetricD7AdRevenueROAS  AcquisitionMetric = "d7AdRevenueRoas"
	MetricD14AdRevenueROAS AcquisitionMetric = "d14AdRevenueRoas"
	MetricD21AdRevenueROAS AcquisitionMetric = "d21AdRevenueRoas"
	MetricD28AdRevenueROAS AcquisitionMetric = "d28AdRevenueRoas"

	MetricD0IAPRevenue  AcquisitionMetric = "d0IapRevenue"
	MetricD1IAPRevenue  AcquisitionMetric = "d1IapRevenue"
	MetricD3IAPRevenue  AcquisitionMetric = "d3IapRevenue"
	MetricD7IAPRevenue  AcquisitionMetric = "d7IapRevenue"
	MetricD14IAPRevenue AcquisitionMetric = "d14IapRevenue"
	MetricD21IAPRevenue AcquisitionMetric = "d21IapRevenue"
	MetricD28IAPRevenue AcquisitionMetric = "d28IapRevenue"

	MetricD0IAPROAS  AcquisitionMetric = "d0IapRoas"
	MetricD1IAPROAS  AcquisitionMetric = "d1IapRoas"
	MetricD3IAPROAS  AcquisitionMetric = "d3IapRoas"
	MetricD7IAPROAS  AcquisitionMetric = "d7IapRoas"
	MetricD14IAPROAS AcquisitionMetric = "d14IapRoas"
	MetricD21IAPROAS AcquisitionMetric = "d21IapRoas"
	MetricD28IAPROAS AcquisitionMetric = "d28IapRoas"

	MetricD0Purchases  AcquisitionMetric = "d0Purchases"
	MetricD1Purchases  AcquisitionMetric = "d1Purchases"
	MetricD3Purchases  AcquisitionMetric = "d3Purchases"
	MetricD7Purchases  AcquisitionMetric = "d7Purchases"
	MetricD14Purchases AcquisitionMetric = "d14Purchases"
	MetricD21Purchases AcquisitionMetric = "d21Purchases"
	MetricD28Purchases AcquisitionMetric = "d28Purchases"

	MetricD0UniquePurchasers  AcquisitionMetric = "d0UniquePurchasers"
	MetricD1UniquePurchasers  AcquisitionMetric = "d1UniquePurchasers"
	MetricD3UniquePurchasers  AcquisitionMetric = "d3UniquePurchasers"
	MetricD7UniquePurchasers  AcquisitionMetric = "d7UniquePurchasers"
	MetricD14UniquePurchasers AcquisitionMetric = "d14UniquePurchasers"
	MetricD21UniquePurchasers AcquisitionMetric = "d21UniquePurchasers"
	MetricD28UniquePurchasers AcquisitionMetric = "d28UniquePurchasers"

	MetricD0Retained  AcquisitionMetric = "d0Retained"
	MetricD1Retained  AcquisitionMetric = "d1Retained"
	MetricD3Retained  AcquisitionMetric = "d3Retained"
	MetricD7Retained  AcquisitionMetric = "d7Retained"
	MetricD14Retained AcquisitionMetric = "d14Retained"
	MetricD21Retained AcquisitionMetric = "d21Retained"
	MetricD28Retained AcquisitionMetric = "d28Retained"

	MetricD0RetentionRate  AcquisitionMetric = "d0RetentionRate"
	MetricD1RetentionRate  AcquisitionMetric = "d1RetentionRate"
	MetricD3RetentionRate  AcquisitionMetric = "d3RetentionRate"
	MetricD7RetentionRate  AcquisitionMetric = "d7RetentionRate"
	MetricD14RetentionRate AcquisitionMetric = "d14RetentionRate"
	MetricD21RetentionRate AcquisitionMetric = "d21RetentionRate"
	MetricD28RetentionRate AcquisitionMetric = "d28RetentionRate"

	MetricD0TotalROAS  AcquisitionMetric = "d0TotalRoas"
	MetricD1TotalROAS  AcquisitionMetric = "d1TotalRoas"
	MetricD3TotalROAS  AcquisitionMetric = "d3TotalRoas"
	MetricD7TotalROAS  AcquisitionMetric = "d7TotalRoas"
	MetricD14TotalROAS AcquisitionMetric = "d14TotalRoas"
	MetricD21TotalROAS AcquisitionMetric = "d21TotalRoas"
	MetricD28TotalROAS AcquisitionMetric = "d28TotalRoas"

	MetricD0LevelComplete  AcquisitionMetric = "d0LevelComplete"
	MetricD1LevelComplete  AcquisitionMetric = "d1LevelComplete"
	MetricD3LevelComplete  AcquisitionMetric = "d3LevelComplete"
	MetricD7LevelComplete  AcquisitionMetric = "d7LevelComplete"
	MetricD14LevelComplete AcquisitionMetric = "d14LevelComplete"
	MetricD21LevelComplete AcquisitionMetric = "d21LevelComplete"
	MetricD28LevelComplete AcquisitionMetric = "d28LevelComplete"

	MetricD0CostPerLevelComplete  AcquisitionMetric = "d0CostPerLevelComplete"
	MetricD1CostPerLevelComplete  AcquisitionMetric = "d1CostPerLevelComplete"
	MetricD3CostPerLevelComplete  AcquisitionMetric = "d3CostPerLevelComplete"
	MetricD7CostPerLevelComplete  AcquisitionMetric = "d7CostPerLevelComplete"
	MetricD14CostPerLevelComplete AcquisitionMetric = "d14CostPerLevelComplete"
	MetricD21CostPerLevelComplete AcquisitionMetric = "d21CostPerLevelComplete"
	MetricD28CostPerLevelComplete AcquisitionMetric = "d28CostPerLevelComplete"

	MetricD0LevelCompleteRate  AcquisitionMetric = "d0LevelCompleteRate"
	MetricD1LevelCompleteRate  AcquisitionMetric = "d1LevelCompleteRate"
	MetricD3LevelCompleteRate  AcquisitionMetric = "d3LevelCompleteRate"
	MetricD7LevelCompleteRate  AcquisitionMetric = "d7LevelCompleteRate"
	MetricD14LevelCompleteRate AcquisitionMetric = "d14LevelCompleteRate"
	MetricD21LevelCompleteRate AcquisitionMetric = "d21LevelCompleteRate"
	MetricD28LevelCompleteRate AcquisitionMetric = "d28LevelCompleteRate"

	MetricD0Payer  AcquisitionMetric = "d0Payer"
	MetricD1Payer  AcquisitionMetric = "d1Payer"
	MetricD3Payer  AcquisitionMetric = "d3Payer"
	MetricD7Payer  AcquisitionMetric = "d7Payer"
	MetricD14Payer AcquisitionMetric = "d14Payer"
	MetricD21Payer AcquisitionMetric = "d21Payer"
	MetricD28Payer AcquisitionMetric = "d28Payer"

	MetricD0PayerRate  AcquisitionMetric = "d0PayerRate"
	MetricD1PayerRate  AcquisitionMetric = "d1PayerRate"
	MetricD3PayerRate  AcquisitionMetric = "d3PayerRate"
	MetricD7PayerRate  AcquisitionMetric = "d7PayerRate"
	MetricD14PayerRate AcquisitionMetric = "d14PayerRate"
	MetricD21PayerRate AcquisitionMetric = "d21PayerRate"
	MetricD28PayerRate AcquisitionMetric = "d28PayerRate"

	MetricD0CostPerPayer  AcquisitionMetric = "d0CostPerPayer"
	MetricD1CostPerPayer  AcquisitionMetric = "d1CostPerPayer"
	MetricD3CostPerPayer  AcquisitionMetric = "d3CostPerPayer"
	MetricD7CostPerPayer  AcquisitionMetric = "d7CostPerPayer"
	MetricD14CostPerPayer AcquisitionMetric = "d14CostPerPayer"
	MetricD21CostPerPayer AcquisitionMetric = "d21CostPerPayer"
	MetricD28CostPerPayer AcquisitionMetric = "d28CostPerPayer"
)

const (
	SKANMetricStarts   SKANMetric = "starts"
	SKANMetricViews    SKANMetric = "views"
	SKANMetricClicks   SKANMetric = "clicks"
	SKANMetricInstalls SKANMetric = "installs"
	SKANMetricSpend    SKANMetric = "spend"
	SKANMetricCPI      SKANMetric = "cpi"
	SKANMetricCVR      SKANMetric = "cvr"
)
